AllCops:
  TargetRubyVersion: 2.6

  Exclude:
    - 'db/schema.rb'
    - 'debounce_io.gemspec'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Style/LambdaCall:
  Enabled: false
